name: Chromatic Workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yaml

  chromatic-deployment:
    name: Chromatic Deployment
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn lint

      - name: Build & Deploy
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook
