name: Chromatic Workflow

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  chromatic-deployment:
    name: Chromatic Deployment
    steps:
      - name: Setup
        uses: ./.github/workflows/setup.yaml

      - name: Lint
        run: yarn lint

      - name: Build & Deploy
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook
