name: Release

on:
	release:
		types: [created]

jobs:
	release:
		name: Release
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v3

			- name: Setup node
				uses: actions/setup-node@v3
				with:
					node-version: 16

      - name: Install packages
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Lint
        run: yarn lint

      # - name: Test
      #   run: yarn test

      - name: Build
        run: yarn build

      - name: Publish
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

